all : SphereFast SphereSlow

SphereFast : SphereFast.cpp
	g++ -o SphereFast SphereFast.cpp -fopenmp -std=c++11 -O3

SphereSlow : SphereSlow.cpp
	g++ -o SphereSlow SphereSlow.cpp -fopenmp -std=c++11 -O3
